/**
 * Keep the upstream Noto font slices needed by this app's source text.
 * Uses only Node APIs and installed @fontsource packages; no network or
 * fontTools dependency. Run before dev/build when changing visible text.
 * Modern browsers receive WOFF2 only. Unlisted dynamic text falls back to
 * the system font stack, while every static Korean/Hanja UI string is local.
 */
import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import { dirname, extname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const output = join(root, 'src/ui/fonts.css');
const fonts = [
  ['noto-sans-kr', 400], ['noto-sans-kr', 500],
  ['noto-sans-kr', 700], ['noto-serif-kr', 600],
];

async function sourceFiles(directory) {
  const files = [];
  for (const entry of (await readdir(directory, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name, 'en'))) {
    const path = join(directory, entry.name);
    if (entry.isDirectory() && !['__tests__', 'fonts'].includes(entry.name)) files.push(...await sourceFiles(path));
    else if (entry.isFile() && ['.ts', '.tsx', '.css'].includes(extname(path))
      && !/\.(test|spec)\.[cm]?[jt]sx?$/.test(entry.name) && path !== output) files.push(path);
  }
  return files;
}

const sources = [...await sourceFiles(join(root, 'src')), join(root, 'index.html')];
const text = (await Promise.all(sources.map(path => readFile(path, 'utf8')))).join('\n');
const points = new Set([...text.normalize('NFC')].map(character => character.codePointAt(0)));
// Digits and status/notation symbols may be composed at runtime.
for (let point = 0x20; point <= 0x7e; point++) points.add(point);
for (const character of '漢楚將士車包馬象卒兵한초궁사차포마상졸병0123456789←↑→↓↔↕·×−–—…') points.add(character.codePointAt(0));
// Support escaped literal Unicode characters in strings as well as direct UTF-8.
for (const match of text.matchAll(/\\u(?:\{([0-9a-fA-F]+)\}|([0-9a-fA-F]{4}))/g)) points.add(Number.parseInt(match[1] ?? match[2], 16));

function ranges(value) {
  return value.split(',').map(part => {
    const match = /^\s*U\+([0-9a-f?]+)(?:-([0-9a-f]+))?\s*$/i.exec(part);
    if (!match) throw new Error(`Unsupported font Unicode range: ${part}`);
    return [Number.parseInt(match[1].replaceAll('?', '0'), 16), Number.parseInt(match[2] ?? match[1].replaceAll('?', 'f'), 16)];
  });
}

const selectedAssets = new Set();
const originalAssets = new Set();
const blocks = [];
for (const [family, weight] of fonts) {
  const packageDirectory = join(root, 'node_modules/@fontsource', family);
  const css = await readFile(join(packageDirectory, `${weight}.css`), 'utf8');
  const faces = css.match(/@font-face\s*\{[^}]+\}/g);
  if (!faces?.length) throw new Error(`No font faces found for ${family} ${weight}`);
  for (const face of faces) {
    for (const match of face.matchAll(/url\(([^)]+)\)/g)) originalAssets.add(resolve(packageDirectory, match[1].replaceAll(/["']/g, '')));
    const unicode = /unicode-range:\s*([^;]+);/.exec(face)?.[1];
    if (!unicode) throw new Error(`Missing unicode-range in ${family} ${weight}`);
    const coverage = ranges(unicode);
    if (![...points].some(point => coverage.some(([start, end]) => point >= start && point <= end))) continue;
    const asset = /url\(([^)]+\.woff2)\)/.exec(face)?.[1];
    if (!asset) throw new Error(`Missing WOFF2 in ${family} ${weight}`);
    const assetPath = resolve(packageDirectory, asset);
    await stat(assetPath); // Fail immediately if a dependency upgrade changes the package layout.
    selectedAssets.add(assetPath);
    const url = relative(dirname(output), assetPath).split('\\').join('/');
    blocks.push(face.replace(/src:[^;]+;/, `src: url('${url}') format('woff2');`));
  }
}

const generated = `/* Generated by scripts/prepare-fonts.mjs. Do not edit manually.
 * ${sources.length} source files, ${points.size} codepoints, ${selectedAssets.size} local WOFF2 slices.
 * Regenerate before dev/build after changing UI text. Font licenses stay in @fontsource packages.
 */\n\n${blocks.join('\n\n')}\n`;
let previous;
try { previous = await readFile(output, 'utf8'); } catch (error) { if (error.code !== 'ENOENT') throw error; }
if (generated !== previous) await writeFile(output, generated);
async function totalBytes(paths) {
  return (await Promise.all([...paths].map(async path => (await stat(path)).size))).reduce((sum, bytes) => sum + bytes, 0);
}
const originalSize = await totalBytes(originalAssets), selectedSize = await totalBytes(selectedAssets);
console.log(`[fonts] ${originalAssets.size} → ${selectedAssets.size} files; ${(originalSize / 1048576).toFixed(2)} → ${(selectedSize / 1048576).toFixed(2)} MiB (${(100 * (1 - selectedSize / originalSize)).toFixed(1)}% smaller)`);
