import { describe, expect, it } from 'vitest'
import { createMatch, gameReducer, viewedGame } from './game-state'

describe('local match reducer', () => {
  it('previews arrangements and starts with Cho', () => {
    const prepared = gameReducer(createMatch(), { type: 'CONFIGURE', settings: { hanSetup: 'SMMS' } })
    expect(prepared.game.board[1]?.type).toBe('SANG')
    const started = gameReducer(prepared, { type: 'START' })
    expect(started.phase).toBe('playing')
    expect(started.game.turn).toBe('CHO')
  })
  it('selects a piece and delegates a legal destination to the engine', () => {
    const started = gameReducer(createMatch(), { type: 'START' })
    const selected = gameReducer(started, { type: 'SELECT', position: { file: 1, rank: 7 } })
    expect(selected.selected).toEqual({ file: 1, rank: 7 })
    const moved = gameReducer(selected, { type: 'SELECT', position: { file: 1, rank: 6 } })
    expect(moved.game.moveHistory).toHaveLength(1)
    expect(moved.game.turn).toBe('HAN')
    expect(moved.selected).toBe(null)
    expect(started.game.moveHistory).toHaveLength(0)
  })
  it('rejects invalid moves without crashing or mutating the game', () => {
    const state = gameReducer(createMatch(), { type: 'START' })
    const next = gameReducer(state, { type: 'MOVE', from: { file: 1, rank: 7 }, to: { file: 1, rank: 8 } })
    expect(next.game).toBe(state.game)
  })
  it('blocks all moves during replay and resumes the untouched live game', () => {
    let state = gameReducer(createMatch(), { type: 'START' })
    state = gameReducer(state, { type: 'PASS' })
    state = gameReducer(state, { type: 'REPLAY', cursor: 0 })
    expect(viewedGame(state).moveHistory).toHaveLength(0)
    expect(gameReducer(state, { type: 'PASS' })).toBe(state)
    expect(gameReducer(state, { type: 'UNDO' })).toBe(state)
    state = gameReducer(state, { type: 'REPLAY', cursor: null })
    expect(viewedGame(state).moveHistory).toHaveLength(1)
  })
  it('freezes at an engine result and can undo back to play', () => {
    let state = gameReducer(createMatch(), { type: 'START' })
    for (let count = 0; count < 4; count += 1) state = gameReducer(state, { type: 'PASS' })
    expect(state.result.reason).toBe('REPETITION')
    expect(gameReducer(state, { type: 'PASS' })).toBe(state)
    state = gameReducer(state, { type: 'UNDO' })
    expect(state.result.status).toBe('PLAYING')
    expect(state.game.moveHistory).toHaveLength(3)
  })
  it('requires a response to an offer before applying agreed score adjudication', () => {
    let state = gameReducer(createMatch(), { type: 'START' })
    state = gameReducer(state, { type: 'OFFER_DRAW' })
    expect(state.drawOffer).toBe('CHO')
    expect(gameReducer(state, { type: 'PASS' })).toBe(state)
    const declined = gameReducer(state, { type: 'DRAW_RESPONSE', accept: false })
    expect(declined.result.status).toBe('PLAYING')
    expect(declined.drawOffer).toBe(null)
    const accepted = gameReducer(state, { type: 'DRAW_RESPONSE', accept: true })
    expect(accepted.result.reason).toBe('AGREEMENT')
    expect(accepted.result.winner).toBe('HAN')
  })
  it('resigns only a live match and pauses the clock during replay', () => {
    let state = gameReducer(createMatch(), { type: 'START' })
    state = gameReducer(state, { type: 'TICK', milliseconds: 1000 })
    expect(state.elapsedMs).toBe(1000)
    const replay = gameReducer(state, { type: 'REPLAY', cursor: 0 })
    expect(gameReducer(replay, { type: 'TICK', milliseconds: 1000 }).elapsedMs).toBe(1000)
    expect(gameReducer(replay, { type: 'RESIGN' })).toBe(replay)
    expect(gameReducer(state, { type: 'RESIGN' }).result.winner).toBe('HAN')
  })
})