import { expect, test } from '@playwright/test'

test('installs assets and restores and plays a full offline session without touching other caches', async ({ page, context, request, baseURL }, info) => {
  await page.addInitScript(() => {
    void caches.open('neighbor-app-cache').then((cache) => cache.put(new URL('neighbor-proof', location.href), new Response('keep')))
  })
  await page.goto(baseURL!)
  await page.evaluate(() => navigator.serviceWorker.ready)
  await expect.poll(() => page.evaluate(() => !!navigator.serviceWorker.controller)).toBe(true)
  await expect(page.getByText('오프라인 준비 완료', { exact: true })).toBeVisible()
  const manifestUrl = new URL((await page.locator('link[rel="manifest"]').getAttribute('href'))!, page.url()).href
  const manifest = await (await request.get(manifestUrl)).json()
  expect(manifest.name).toBe('Astra 장기')
  for (const icon of manifest.icons) {
    const response = await request.get(new URL(icon.src, manifestUrl).href)
    expect(response.ok()).toBe(true)
    const image = await response.body()
    expect(image.readUInt32BE(16)).toBe(Number(icon.sizes.split('x')[0]))
  }
  const cacheNames = await page.evaluate(() => caches.keys())
  expect(cacheNames).toContain('neighbor-app-cache')
  expect(cacheNames.some((name) => name.startsWith('astra-janggi'))).toBe(true)

  await page.getByRole('button', { name: info.project.name === 'mobile' ? '바로 대국 시작' : '대국 시작', exact: true }).click()
  await page.locator('[data-position="5,7"]').focus()
  await page.keyboard.press('Enter')
  await page.keyboard.press('ArrowUp')
  await page.keyboard.press('Enter')
  await expect(page.locator('.move-entry')).toHaveCount(1)
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('dialog', { name: '이전 대국을 이어둘까요?' })).toBeVisible()
  await page.getByRole('button', { name: '이어서 두기', exact: true }).click()
  await expect(page.getByText('오프라인', { exact: true })).toBeVisible()
  await expect(page.locator('[data-piece-id]')).toHaveCount(32)
  await expect(page.locator('[data-position="5,6"]')).toHaveAttribute('aria-label', '초 졸, 6행 5열')
  await page.locator('[data-position="1,4"]').focus()
  await page.keyboard.press('Enter')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(page.locator('.move-entry')).toHaveCount(2)
  await page.getByRole('button', { name: '화면 설정', exact: true }).click()
  await page.getByRole('radio', { name: '한 한글', exact: true }).check()
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-piece-id="CHO-GUNG-5-9"] .piece-character')).toHaveText('궁')
  await page.reload()
  await page.getByRole('button', { name: '이어서 두기', exact: true }).click()
  await expect(page.locator('.move-entry')).toHaveCount(2)
  await expect(page.locator('[data-piece-id="CHO-GUNG-5-9"] .piece-character')).toHaveText('궁')
  await page.screenshot({ path: `test-results/offline/${info.project.name}.png`, fullPage: true })
})